name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (or `patch`, `minor`, or `major`)"
        required: true
        type: string
      VSCE_PAT:
        description: "Access token for marketplace.visualstudio.com, generated through https://dev.azure.com/tomodachi94/_usersSettings/tokens"
        required: true
        type: string
      OVSX_PAT:
        description: "Access token for open-vsx.org, generated through https://open-vsx.org/user-settings/tokens"
        type: string
permissions:
  # We need to be able to:
  # - push a tag
  # - create a GitHub Release
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm run release "$VERSION" --ci
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ inputs.VSCE_PAT }}
          OVSX_PAT: ${{ inputs.OVSX_PAT }}
